easy_admin:
  entities:
  - App\Entity\User
  - App\Entity\Article
  - App\Entity\Comment
  - App\Entity\Tag

  site_name:
    'BlogAdmin'
  design:
    brand_color: '#6151E2'
    form_theme:
    - '@EasyAdmin/form/bootstrap_4.html.twig'


